# Generated by Django 5.1.7 on 2025-03-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=255, unique=True)),
                ('book_title', models.CharField(max_length=255)),
                ('borrowed_book', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
