# Generated by Django 5.1.7 on 2026-04-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DueBooks', '0002_borrowrecord_returned_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
